name: 'Upload to S3'
description: 'Upload file or folder to S3'

inputs:
  AWS_BUCKET_NAME:
    description: 'Where to upload the file or folder'
    required: true

  AWS_REGION:
    description: 'Region to connect on S3 and upload file or folder'
    required: false
    default: "us-east-1"

  AWS_SECRET_ACCESS_KEY:
    required: true
    description: "AWS Secret Access Key to connect on AWS"

  AWS_ACCESS_KEY_ID:
    required: true
    description: "AWS Access Key Id to connect on AWS"

  local_path_upload:
    description: "path to the file or folder to upload"
    required: true

  bucket_path_upload:
    description: "path to save the file or folder on AWS S3"
    required: false
    default: "/"

  is_directory:
    description: "is directory to upload or not"
    required: false
    default: "false"

  zip:
    description: "need zip the file/folder"
    required: false
    default: "true"

  name_to_save_on_s3:
    description: "the name of folder or file that be saved in s3"
    required: true

  acl:
    description: "the ACL to save the object on S3"
    required: false
    default: "public-read"

  storage_class:
    description: "the type of storage class to save in s3"
    required: false
    default: "STANDARD"

  tags:
    description: "the tags to put on object"
    required: false
    default: "Source=github-actions&Environment=production"

runs:
  using: 'node16'
  main: 'dist/index.js'
